FROM %REPLACE_FROM%
################################################################################
# OPEN CV
###############################################################################
WORKDIR /mnt/compiled/dependencies/
# TODO: download this from somewhere?
COPY opencv opencv

